name: Generate Packages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install dpkg-dev gzip bzip2 -y

    - name: Generate Packages
      run: |
        dpkg-scanpackages -m debs/ > Packages
        gzip -c Packages > Packages.gz
        bzip2 -k Packages

    - name: Commit and Push Changes
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git add Packages Packages.gz Packages.bz2
        git commit -m "Generate Packages"
        git push
